# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cfarmer/p/draco

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cfarmer/p/draco-javascript

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.8.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cfarmer/p/draco-javascript/CMakeFiles /Users/cfarmer/p/draco-javascript/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cfarmer/p/draco-javascript/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named draco_decoder

# Build rule for target.
draco_decoder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 draco_decoder
.PHONY : draco_decoder

# fast build rule for target.
draco_decoder/fast:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/build
.PHONY : draco_decoder/fast

#=============================================================================
# Target rules for targets named draco_decoder_2_finalize_js

# Build rule for target.
draco_decoder_2_finalize_js: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 draco_decoder_2_finalize_js
.PHONY : draco_decoder_2_finalize_js

# fast build rule for target.
draco_decoder_2_finalize_js/fast:
	$(MAKE) -f CMakeFiles/draco_decoder_2_finalize_js.dir/build.make CMakeFiles/draco_decoder_2_finalize_js.dir/build
.PHONY : draco_decoder_2_finalize_js/fast

#=============================================================================
# Target rules for targets named draco_decoder_1_glue_js

# Build rule for target.
draco_decoder_1_glue_js: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 draco_decoder_1_glue_js
.PHONY : draco_decoder_1_glue_js

# fast build rule for target.
draco_decoder_1_glue_js/fast:
	$(MAKE) -f CMakeFiles/draco_decoder_1_glue_js.dir/build.make CMakeFiles/draco_decoder_1_glue_js.dir/build
.PHONY : draco_decoder_1_glue_js/fast

#=============================================================================
# Target rules for targets named draco_decoder_2_version_js

# Build rule for target.
draco_decoder_2_version_js: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 draco_decoder_2_version_js
.PHONY : draco_decoder_2_version_js

# fast build rule for target.
draco_decoder_2_version_js/fast:
	$(MAKE) -f CMakeFiles/draco_decoder_2_version_js.dir/build.make CMakeFiles/draco_decoder_2_version_js.dir/build
.PHONY : draco_decoder_2_version_js/fast

#=============================================================================
# Target rules for targets named draco_decoder_1_prepareCallbacks_js

# Build rule for target.
draco_decoder_1_prepareCallbacks_js: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 draco_decoder_1_prepareCallbacks_js
.PHONY : draco_decoder_1_prepareCallbacks_js

# fast build rule for target.
draco_decoder_1_prepareCallbacks_js/fast:
	$(MAKE) -f CMakeFiles/draco_decoder_1_prepareCallbacks_js.dir/build.make CMakeFiles/draco_decoder_1_prepareCallbacks_js.dir/build
.PHONY : draco_decoder_1_prepareCallbacks_js/fast

compression/attributes/attributes_decoder.o: compression/attributes/attributes_decoder.cc.o

.PHONY : compression/attributes/attributes_decoder.o

# target to build an object file
compression/attributes/attributes_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/attributes_decoder.cc.o
.PHONY : compression/attributes/attributes_decoder.cc.o

compression/attributes/attributes_decoder.i: compression/attributes/attributes_decoder.cc.i

.PHONY : compression/attributes/attributes_decoder.i

# target to preprocess a source file
compression/attributes/attributes_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/attributes_decoder.cc.i
.PHONY : compression/attributes/attributes_decoder.cc.i

compression/attributes/attributes_decoder.s: compression/attributes/attributes_decoder.cc.s

.PHONY : compression/attributes/attributes_decoder.s

# target to generate assembly for a file
compression/attributes/attributes_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/attributes_decoder.cc.s
.PHONY : compression/attributes/attributes_decoder.cc.s

compression/attributes/kd_tree_attributes_decoder.o: compression/attributes/kd_tree_attributes_decoder.cc.o

.PHONY : compression/attributes/kd_tree_attributes_decoder.o

# target to build an object file
compression/attributes/kd_tree_attributes_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/kd_tree_attributes_decoder.cc.o
.PHONY : compression/attributes/kd_tree_attributes_decoder.cc.o

compression/attributes/kd_tree_attributes_decoder.i: compression/attributes/kd_tree_attributes_decoder.cc.i

.PHONY : compression/attributes/kd_tree_attributes_decoder.i

# target to preprocess a source file
compression/attributes/kd_tree_attributes_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/kd_tree_attributes_decoder.cc.i
.PHONY : compression/attributes/kd_tree_attributes_decoder.cc.i

compression/attributes/kd_tree_attributes_decoder.s: compression/attributes/kd_tree_attributes_decoder.cc.s

.PHONY : compression/attributes/kd_tree_attributes_decoder.s

# target to generate assembly for a file
compression/attributes/kd_tree_attributes_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/kd_tree_attributes_decoder.cc.s
.PHONY : compression/attributes/kd_tree_attributes_decoder.cc.s

compression/attributes/sequential_attribute_decoder.o: compression/attributes/sequential_attribute_decoder.cc.o

.PHONY : compression/attributes/sequential_attribute_decoder.o

# target to build an object file
compression/attributes/sequential_attribute_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_attribute_decoder.cc.o
.PHONY : compression/attributes/sequential_attribute_decoder.cc.o

compression/attributes/sequential_attribute_decoder.i: compression/attributes/sequential_attribute_decoder.cc.i

.PHONY : compression/attributes/sequential_attribute_decoder.i

# target to preprocess a source file
compression/attributes/sequential_attribute_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_attribute_decoder.cc.i
.PHONY : compression/attributes/sequential_attribute_decoder.cc.i

compression/attributes/sequential_attribute_decoder.s: compression/attributes/sequential_attribute_decoder.cc.s

.PHONY : compression/attributes/sequential_attribute_decoder.s

# target to generate assembly for a file
compression/attributes/sequential_attribute_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_attribute_decoder.cc.s
.PHONY : compression/attributes/sequential_attribute_decoder.cc.s

compression/attributes/sequential_attribute_decoders_controller.o: compression/attributes/sequential_attribute_decoders_controller.cc.o

.PHONY : compression/attributes/sequential_attribute_decoders_controller.o

# target to build an object file
compression/attributes/sequential_attribute_decoders_controller.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_attribute_decoders_controller.cc.o
.PHONY : compression/attributes/sequential_attribute_decoders_controller.cc.o

compression/attributes/sequential_attribute_decoders_controller.i: compression/attributes/sequential_attribute_decoders_controller.cc.i

.PHONY : compression/attributes/sequential_attribute_decoders_controller.i

# target to preprocess a source file
compression/attributes/sequential_attribute_decoders_controller.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_attribute_decoders_controller.cc.i
.PHONY : compression/attributes/sequential_attribute_decoders_controller.cc.i

compression/attributes/sequential_attribute_decoders_controller.s: compression/attributes/sequential_attribute_decoders_controller.cc.s

.PHONY : compression/attributes/sequential_attribute_decoders_controller.s

# target to generate assembly for a file
compression/attributes/sequential_attribute_decoders_controller.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_attribute_decoders_controller.cc.s
.PHONY : compression/attributes/sequential_attribute_decoders_controller.cc.s

compression/attributes/sequential_integer_attribute_decoder.o: compression/attributes/sequential_integer_attribute_decoder.cc.o

.PHONY : compression/attributes/sequential_integer_attribute_decoder.o

# target to build an object file
compression/attributes/sequential_integer_attribute_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_integer_attribute_decoder.cc.o
.PHONY : compression/attributes/sequential_integer_attribute_decoder.cc.o

compression/attributes/sequential_integer_attribute_decoder.i: compression/attributes/sequential_integer_attribute_decoder.cc.i

.PHONY : compression/attributes/sequential_integer_attribute_decoder.i

# target to preprocess a source file
compression/attributes/sequential_integer_attribute_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_integer_attribute_decoder.cc.i
.PHONY : compression/attributes/sequential_integer_attribute_decoder.cc.i

compression/attributes/sequential_integer_attribute_decoder.s: compression/attributes/sequential_integer_attribute_decoder.cc.s

.PHONY : compression/attributes/sequential_integer_attribute_decoder.s

# target to generate assembly for a file
compression/attributes/sequential_integer_attribute_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_integer_attribute_decoder.cc.s
.PHONY : compression/attributes/sequential_integer_attribute_decoder.cc.s

compression/attributes/sequential_normal_attribute_decoder.o: compression/attributes/sequential_normal_attribute_decoder.cc.o

.PHONY : compression/attributes/sequential_normal_attribute_decoder.o

# target to build an object file
compression/attributes/sequential_normal_attribute_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_normal_attribute_decoder.cc.o
.PHONY : compression/attributes/sequential_normal_attribute_decoder.cc.o

compression/attributes/sequential_normal_attribute_decoder.i: compression/attributes/sequential_normal_attribute_decoder.cc.i

.PHONY : compression/attributes/sequential_normal_attribute_decoder.i

# target to preprocess a source file
compression/attributes/sequential_normal_attribute_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_normal_attribute_decoder.cc.i
.PHONY : compression/attributes/sequential_normal_attribute_decoder.cc.i

compression/attributes/sequential_normal_attribute_decoder.s: compression/attributes/sequential_normal_attribute_decoder.cc.s

.PHONY : compression/attributes/sequential_normal_attribute_decoder.s

# target to generate assembly for a file
compression/attributes/sequential_normal_attribute_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_normal_attribute_decoder.cc.s
.PHONY : compression/attributes/sequential_normal_attribute_decoder.cc.s

compression/attributes/sequential_quantization_attribute_decoder.o: compression/attributes/sequential_quantization_attribute_decoder.cc.o

.PHONY : compression/attributes/sequential_quantization_attribute_decoder.o

# target to build an object file
compression/attributes/sequential_quantization_attribute_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_quantization_attribute_decoder.cc.o
.PHONY : compression/attributes/sequential_quantization_attribute_decoder.cc.o

compression/attributes/sequential_quantization_attribute_decoder.i: compression/attributes/sequential_quantization_attribute_decoder.cc.i

.PHONY : compression/attributes/sequential_quantization_attribute_decoder.i

# target to preprocess a source file
compression/attributes/sequential_quantization_attribute_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_quantization_attribute_decoder.cc.i
.PHONY : compression/attributes/sequential_quantization_attribute_decoder.cc.i

compression/attributes/sequential_quantization_attribute_decoder.s: compression/attributes/sequential_quantization_attribute_decoder.cc.s

.PHONY : compression/attributes/sequential_quantization_attribute_decoder.s

# target to generate assembly for a file
compression/attributes/sequential_quantization_attribute_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/attributes/sequential_quantization_attribute_decoder.cc.s
.PHONY : compression/attributes/sequential_quantization_attribute_decoder.cc.s

compression/decode.o: compression/decode.cc.o

.PHONY : compression/decode.o

# target to build an object file
compression/decode.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/decode.cc.o
.PHONY : compression/decode.cc.o

compression/decode.i: compression/decode.cc.i

.PHONY : compression/decode.i

# target to preprocess a source file
compression/decode.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/decode.cc.i
.PHONY : compression/decode.cc.i

compression/decode.s: compression/decode.cc.s

.PHONY : compression/decode.s

# target to generate assembly for a file
compression/decode.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/decode.cc.s
.PHONY : compression/decode.cc.s

compression/mesh/mesh_decoder.o: compression/mesh/mesh_decoder.cc.o

.PHONY : compression/mesh/mesh_decoder.o

# target to build an object file
compression/mesh/mesh_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_decoder.cc.o
.PHONY : compression/mesh/mesh_decoder.cc.o

compression/mesh/mesh_decoder.i: compression/mesh/mesh_decoder.cc.i

.PHONY : compression/mesh/mesh_decoder.i

# target to preprocess a source file
compression/mesh/mesh_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_decoder.cc.i
.PHONY : compression/mesh/mesh_decoder.cc.i

compression/mesh/mesh_decoder.s: compression/mesh/mesh_decoder.cc.s

.PHONY : compression/mesh/mesh_decoder.s

# target to generate assembly for a file
compression/mesh/mesh_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_decoder.cc.s
.PHONY : compression/mesh/mesh_decoder.cc.s

compression/mesh/mesh_edgebreaker_decoder.o: compression/mesh/mesh_edgebreaker_decoder.cc.o

.PHONY : compression/mesh/mesh_edgebreaker_decoder.o

# target to build an object file
compression/mesh/mesh_edgebreaker_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_edgebreaker_decoder.cc.o
.PHONY : compression/mesh/mesh_edgebreaker_decoder.cc.o

compression/mesh/mesh_edgebreaker_decoder.i: compression/mesh/mesh_edgebreaker_decoder.cc.i

.PHONY : compression/mesh/mesh_edgebreaker_decoder.i

# target to preprocess a source file
compression/mesh/mesh_edgebreaker_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_edgebreaker_decoder.cc.i
.PHONY : compression/mesh/mesh_edgebreaker_decoder.cc.i

compression/mesh/mesh_edgebreaker_decoder.s: compression/mesh/mesh_edgebreaker_decoder.cc.s

.PHONY : compression/mesh/mesh_edgebreaker_decoder.s

# target to generate assembly for a file
compression/mesh/mesh_edgebreaker_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_edgebreaker_decoder.cc.s
.PHONY : compression/mesh/mesh_edgebreaker_decoder.cc.s

compression/mesh/mesh_edgebreaker_decoder_impl.o: compression/mesh/mesh_edgebreaker_decoder_impl.cc.o

.PHONY : compression/mesh/mesh_edgebreaker_decoder_impl.o

# target to build an object file
compression/mesh/mesh_edgebreaker_decoder_impl.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_edgebreaker_decoder_impl.cc.o
.PHONY : compression/mesh/mesh_edgebreaker_decoder_impl.cc.o

compression/mesh/mesh_edgebreaker_decoder_impl.i: compression/mesh/mesh_edgebreaker_decoder_impl.cc.i

.PHONY : compression/mesh/mesh_edgebreaker_decoder_impl.i

# target to preprocess a source file
compression/mesh/mesh_edgebreaker_decoder_impl.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_edgebreaker_decoder_impl.cc.i
.PHONY : compression/mesh/mesh_edgebreaker_decoder_impl.cc.i

compression/mesh/mesh_edgebreaker_decoder_impl.s: compression/mesh/mesh_edgebreaker_decoder_impl.cc.s

.PHONY : compression/mesh/mesh_edgebreaker_decoder_impl.s

# target to generate assembly for a file
compression/mesh/mesh_edgebreaker_decoder_impl.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_edgebreaker_decoder_impl.cc.s
.PHONY : compression/mesh/mesh_edgebreaker_decoder_impl.cc.s

compression/mesh/mesh_sequential_decoder.o: compression/mesh/mesh_sequential_decoder.cc.o

.PHONY : compression/mesh/mesh_sequential_decoder.o

# target to build an object file
compression/mesh/mesh_sequential_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_sequential_decoder.cc.o
.PHONY : compression/mesh/mesh_sequential_decoder.cc.o

compression/mesh/mesh_sequential_decoder.i: compression/mesh/mesh_sequential_decoder.cc.i

.PHONY : compression/mesh/mesh_sequential_decoder.i

# target to preprocess a source file
compression/mesh/mesh_sequential_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_sequential_decoder.cc.i
.PHONY : compression/mesh/mesh_sequential_decoder.cc.i

compression/mesh/mesh_sequential_decoder.s: compression/mesh/mesh_sequential_decoder.cc.s

.PHONY : compression/mesh/mesh_sequential_decoder.s

# target to generate assembly for a file
compression/mesh/mesh_sequential_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/mesh/mesh_sequential_decoder.cc.s
.PHONY : compression/mesh/mesh_sequential_decoder.cc.s

compression/point_cloud/algorithms/float_points_tree_decoder.o: compression/point_cloud/algorithms/float_points_tree_decoder.cc.o

.PHONY : compression/point_cloud/algorithms/float_points_tree_decoder.o

# target to build an object file
compression/point_cloud/algorithms/float_points_tree_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/algorithms/float_points_tree_decoder.cc.o
.PHONY : compression/point_cloud/algorithms/float_points_tree_decoder.cc.o

compression/point_cloud/algorithms/float_points_tree_decoder.i: compression/point_cloud/algorithms/float_points_tree_decoder.cc.i

.PHONY : compression/point_cloud/algorithms/float_points_tree_decoder.i

# target to preprocess a source file
compression/point_cloud/algorithms/float_points_tree_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/algorithms/float_points_tree_decoder.cc.i
.PHONY : compression/point_cloud/algorithms/float_points_tree_decoder.cc.i

compression/point_cloud/algorithms/float_points_tree_decoder.s: compression/point_cloud/algorithms/float_points_tree_decoder.cc.s

.PHONY : compression/point_cloud/algorithms/float_points_tree_decoder.s

# target to generate assembly for a file
compression/point_cloud/algorithms/float_points_tree_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/algorithms/float_points_tree_decoder.cc.s
.PHONY : compression/point_cloud/algorithms/float_points_tree_decoder.cc.s

compression/point_cloud/algorithms/integer_points_kd_tree_decoder.o: compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.o

.PHONY : compression/point_cloud/algorithms/integer_points_kd_tree_decoder.o

# target to build an object file
compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.o
.PHONY : compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.o

compression/point_cloud/algorithms/integer_points_kd_tree_decoder.i: compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.i

.PHONY : compression/point_cloud/algorithms/integer_points_kd_tree_decoder.i

# target to preprocess a source file
compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.i
.PHONY : compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.i

compression/point_cloud/algorithms/integer_points_kd_tree_decoder.s: compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.s

.PHONY : compression/point_cloud/algorithms/integer_points_kd_tree_decoder.s

# target to generate assembly for a file
compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.s
.PHONY : compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc.s

compression/point_cloud/point_cloud_decoder.o: compression/point_cloud/point_cloud_decoder.cc.o

.PHONY : compression/point_cloud/point_cloud_decoder.o

# target to build an object file
compression/point_cloud/point_cloud_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_decoder.cc.o
.PHONY : compression/point_cloud/point_cloud_decoder.cc.o

compression/point_cloud/point_cloud_decoder.i: compression/point_cloud/point_cloud_decoder.cc.i

.PHONY : compression/point_cloud/point_cloud_decoder.i

# target to preprocess a source file
compression/point_cloud/point_cloud_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_decoder.cc.i
.PHONY : compression/point_cloud/point_cloud_decoder.cc.i

compression/point_cloud/point_cloud_decoder.s: compression/point_cloud/point_cloud_decoder.cc.s

.PHONY : compression/point_cloud/point_cloud_decoder.s

# target to generate assembly for a file
compression/point_cloud/point_cloud_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_decoder.cc.s
.PHONY : compression/point_cloud/point_cloud_decoder.cc.s

compression/point_cloud/point_cloud_kd_tree_decoder.o: compression/point_cloud/point_cloud_kd_tree_decoder.cc.o

.PHONY : compression/point_cloud/point_cloud_kd_tree_decoder.o

# target to build an object file
compression/point_cloud/point_cloud_kd_tree_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_kd_tree_decoder.cc.o
.PHONY : compression/point_cloud/point_cloud_kd_tree_decoder.cc.o

compression/point_cloud/point_cloud_kd_tree_decoder.i: compression/point_cloud/point_cloud_kd_tree_decoder.cc.i

.PHONY : compression/point_cloud/point_cloud_kd_tree_decoder.i

# target to preprocess a source file
compression/point_cloud/point_cloud_kd_tree_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_kd_tree_decoder.cc.i
.PHONY : compression/point_cloud/point_cloud_kd_tree_decoder.cc.i

compression/point_cloud/point_cloud_kd_tree_decoder.s: compression/point_cloud/point_cloud_kd_tree_decoder.cc.s

.PHONY : compression/point_cloud/point_cloud_kd_tree_decoder.s

# target to generate assembly for a file
compression/point_cloud/point_cloud_kd_tree_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_kd_tree_decoder.cc.s
.PHONY : compression/point_cloud/point_cloud_kd_tree_decoder.cc.s

compression/point_cloud/point_cloud_sequential_decoder.o: compression/point_cloud/point_cloud_sequential_decoder.cc.o

.PHONY : compression/point_cloud/point_cloud_sequential_decoder.o

# target to build an object file
compression/point_cloud/point_cloud_sequential_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_sequential_decoder.cc.o
.PHONY : compression/point_cloud/point_cloud_sequential_decoder.cc.o

compression/point_cloud/point_cloud_sequential_decoder.i: compression/point_cloud/point_cloud_sequential_decoder.cc.i

.PHONY : compression/point_cloud/point_cloud_sequential_decoder.i

# target to preprocess a source file
compression/point_cloud/point_cloud_sequential_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_sequential_decoder.cc.i
.PHONY : compression/point_cloud/point_cloud_sequential_decoder.cc.i

compression/point_cloud/point_cloud_sequential_decoder.s: compression/point_cloud/point_cloud_sequential_decoder.cc.s

.PHONY : compression/point_cloud/point_cloud_sequential_decoder.s

# target to generate assembly for a file
compression/point_cloud/point_cloud_sequential_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/compression/point_cloud/point_cloud_sequential_decoder.cc.s
.PHONY : compression/point_cloud/point_cloud_sequential_decoder.cc.s

core/adaptive_rans_bit_decoder.o: core/adaptive_rans_bit_decoder.cc.o

.PHONY : core/adaptive_rans_bit_decoder.o

# target to build an object file
core/adaptive_rans_bit_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/adaptive_rans_bit_decoder.cc.o
.PHONY : core/adaptive_rans_bit_decoder.cc.o

core/adaptive_rans_bit_decoder.i: core/adaptive_rans_bit_decoder.cc.i

.PHONY : core/adaptive_rans_bit_decoder.i

# target to preprocess a source file
core/adaptive_rans_bit_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/adaptive_rans_bit_decoder.cc.i
.PHONY : core/adaptive_rans_bit_decoder.cc.i

core/adaptive_rans_bit_decoder.s: core/adaptive_rans_bit_decoder.cc.s

.PHONY : core/adaptive_rans_bit_decoder.s

# target to generate assembly for a file
core/adaptive_rans_bit_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/adaptive_rans_bit_decoder.cc.s
.PHONY : core/adaptive_rans_bit_decoder.cc.s

core/adaptive_rans_bit_encoder.o: core/adaptive_rans_bit_encoder.cc.o

.PHONY : core/adaptive_rans_bit_encoder.o

# target to build an object file
core/adaptive_rans_bit_encoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/adaptive_rans_bit_encoder.cc.o
.PHONY : core/adaptive_rans_bit_encoder.cc.o

core/adaptive_rans_bit_encoder.i: core/adaptive_rans_bit_encoder.cc.i

.PHONY : core/adaptive_rans_bit_encoder.i

# target to preprocess a source file
core/adaptive_rans_bit_encoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/adaptive_rans_bit_encoder.cc.i
.PHONY : core/adaptive_rans_bit_encoder.cc.i

core/adaptive_rans_bit_encoder.s: core/adaptive_rans_bit_encoder.cc.s

.PHONY : core/adaptive_rans_bit_encoder.s

# target to generate assembly for a file
core/adaptive_rans_bit_encoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/adaptive_rans_bit_encoder.cc.s
.PHONY : core/adaptive_rans_bit_encoder.cc.s

core/bit_coder.o: core/bit_coder.cc.o

.PHONY : core/bit_coder.o

# target to build an object file
core/bit_coder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/bit_coder.cc.o
.PHONY : core/bit_coder.cc.o

core/bit_coder.i: core/bit_coder.cc.i

.PHONY : core/bit_coder.i

# target to preprocess a source file
core/bit_coder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/bit_coder.cc.i
.PHONY : core/bit_coder.cc.i

core/bit_coder.s: core/bit_coder.cc.s

.PHONY : core/bit_coder.s

# target to generate assembly for a file
core/bit_coder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/bit_coder.cc.s
.PHONY : core/bit_coder.cc.s

core/cycle_timer.o: core/cycle_timer.cc.o

.PHONY : core/cycle_timer.o

# target to build an object file
core/cycle_timer.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/cycle_timer.cc.o
.PHONY : core/cycle_timer.cc.o

core/cycle_timer.i: core/cycle_timer.cc.i

.PHONY : core/cycle_timer.i

# target to preprocess a source file
core/cycle_timer.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/cycle_timer.cc.i
.PHONY : core/cycle_timer.cc.i

core/cycle_timer.s: core/cycle_timer.cc.s

.PHONY : core/cycle_timer.s

# target to generate assembly for a file
core/cycle_timer.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/cycle_timer.cc.s
.PHONY : core/cycle_timer.cc.s

core/data_buffer.o: core/data_buffer.cc.o

.PHONY : core/data_buffer.o

# target to build an object file
core/data_buffer.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/data_buffer.cc.o
.PHONY : core/data_buffer.cc.o

core/data_buffer.i: core/data_buffer.cc.i

.PHONY : core/data_buffer.i

# target to preprocess a source file
core/data_buffer.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/data_buffer.cc.i
.PHONY : core/data_buffer.cc.i

core/data_buffer.s: core/data_buffer.cc.s

.PHONY : core/data_buffer.s

# target to generate assembly for a file
core/data_buffer.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/data_buffer.cc.s
.PHONY : core/data_buffer.cc.s

core/decoder_buffer.o: core/decoder_buffer.cc.o

.PHONY : core/decoder_buffer.o

# target to build an object file
core/decoder_buffer.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/decoder_buffer.cc.o
.PHONY : core/decoder_buffer.cc.o

core/decoder_buffer.i: core/decoder_buffer.cc.i

.PHONY : core/decoder_buffer.i

# target to preprocess a source file
core/decoder_buffer.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/decoder_buffer.cc.i
.PHONY : core/decoder_buffer.cc.i

core/decoder_buffer.s: core/decoder_buffer.cc.s

.PHONY : core/decoder_buffer.s

# target to generate assembly for a file
core/decoder_buffer.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/decoder_buffer.cc.s
.PHONY : core/decoder_buffer.cc.s

core/direct_bit_decoder.o: core/direct_bit_decoder.cc.o

.PHONY : core/direct_bit_decoder.o

# target to build an object file
core/direct_bit_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/direct_bit_decoder.cc.o
.PHONY : core/direct_bit_decoder.cc.o

core/direct_bit_decoder.i: core/direct_bit_decoder.cc.i

.PHONY : core/direct_bit_decoder.i

# target to preprocess a source file
core/direct_bit_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/direct_bit_decoder.cc.i
.PHONY : core/direct_bit_decoder.cc.i

core/direct_bit_decoder.s: core/direct_bit_decoder.cc.s

.PHONY : core/direct_bit_decoder.s

# target to generate assembly for a file
core/direct_bit_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/direct_bit_decoder.cc.s
.PHONY : core/direct_bit_decoder.cc.s

core/direct_bit_encoder.o: core/direct_bit_encoder.cc.o

.PHONY : core/direct_bit_encoder.o

# target to build an object file
core/direct_bit_encoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/direct_bit_encoder.cc.o
.PHONY : core/direct_bit_encoder.cc.o

core/direct_bit_encoder.i: core/direct_bit_encoder.cc.i

.PHONY : core/direct_bit_encoder.i

# target to preprocess a source file
core/direct_bit_encoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/direct_bit_encoder.cc.i
.PHONY : core/direct_bit_encoder.cc.i

core/direct_bit_encoder.s: core/direct_bit_encoder.cc.s

.PHONY : core/direct_bit_encoder.s

# target to generate assembly for a file
core/direct_bit_encoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/direct_bit_encoder.cc.s
.PHONY : core/direct_bit_encoder.cc.s

core/divide.o: core/divide.cc.o

.PHONY : core/divide.o

# target to build an object file
core/divide.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/divide.cc.o
.PHONY : core/divide.cc.o

core/divide.i: core/divide.cc.i

.PHONY : core/divide.i

# target to preprocess a source file
core/divide.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/divide.cc.i
.PHONY : core/divide.cc.i

core/divide.s: core/divide.cc.s

.PHONY : core/divide.s

# target to generate assembly for a file
core/divide.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/divide.cc.s
.PHONY : core/divide.cc.s

core/draco_types.o: core/draco_types.cc.o

.PHONY : core/draco_types.o

# target to build an object file
core/draco_types.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/draco_types.cc.o
.PHONY : core/draco_types.cc.o

core/draco_types.i: core/draco_types.cc.i

.PHONY : core/draco_types.i

# target to preprocess a source file
core/draco_types.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/draco_types.cc.i
.PHONY : core/draco_types.cc.i

core/draco_types.s: core/draco_types.cc.s

.PHONY : core/draco_types.s

# target to generate assembly for a file
core/draco_types.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/draco_types.cc.s
.PHONY : core/draco_types.cc.s

core/encoder_buffer.o: core/encoder_buffer.cc.o

.PHONY : core/encoder_buffer.o

# target to build an object file
core/encoder_buffer.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/encoder_buffer.cc.o
.PHONY : core/encoder_buffer.cc.o

core/encoder_buffer.i: core/encoder_buffer.cc.i

.PHONY : core/encoder_buffer.i

# target to preprocess a source file
core/encoder_buffer.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/encoder_buffer.cc.i
.PHONY : core/encoder_buffer.cc.i

core/encoder_buffer.s: core/encoder_buffer.cc.s

.PHONY : core/encoder_buffer.s

# target to generate assembly for a file
core/encoder_buffer.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/encoder_buffer.cc.s
.PHONY : core/encoder_buffer.cc.s

core/hash_utils.o: core/hash_utils.cc.o

.PHONY : core/hash_utils.o

# target to build an object file
core/hash_utils.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/hash_utils.cc.o
.PHONY : core/hash_utils.cc.o

core/hash_utils.i: core/hash_utils.cc.i

.PHONY : core/hash_utils.i

# target to preprocess a source file
core/hash_utils.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/hash_utils.cc.i
.PHONY : core/hash_utils.cc.i

core/hash_utils.s: core/hash_utils.cc.s

.PHONY : core/hash_utils.s

# target to generate assembly for a file
core/hash_utils.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/hash_utils.cc.s
.PHONY : core/hash_utils.cc.s

core/options.o: core/options.cc.o

.PHONY : core/options.o

# target to build an object file
core/options.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/options.cc.o
.PHONY : core/options.cc.o

core/options.i: core/options.cc.i

.PHONY : core/options.i

# target to preprocess a source file
core/options.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/options.cc.i
.PHONY : core/options.cc.i

core/options.s: core/options.cc.s

.PHONY : core/options.s

# target to generate assembly for a file
core/options.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/options.cc.s
.PHONY : core/options.cc.s

core/quantization_utils.o: core/quantization_utils.cc.o

.PHONY : core/quantization_utils.o

# target to build an object file
core/quantization_utils.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/quantization_utils.cc.o
.PHONY : core/quantization_utils.cc.o

core/quantization_utils.i: core/quantization_utils.cc.i

.PHONY : core/quantization_utils.i

# target to preprocess a source file
core/quantization_utils.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/quantization_utils.cc.i
.PHONY : core/quantization_utils.cc.i

core/quantization_utils.s: core/quantization_utils.cc.s

.PHONY : core/quantization_utils.s

# target to generate assembly for a file
core/quantization_utils.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/quantization_utils.cc.s
.PHONY : core/quantization_utils.cc.s

core/rans_bit_decoder.o: core/rans_bit_decoder.cc.o

.PHONY : core/rans_bit_decoder.o

# target to build an object file
core/rans_bit_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/rans_bit_decoder.cc.o
.PHONY : core/rans_bit_decoder.cc.o

core/rans_bit_decoder.i: core/rans_bit_decoder.cc.i

.PHONY : core/rans_bit_decoder.i

# target to preprocess a source file
core/rans_bit_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/rans_bit_decoder.cc.i
.PHONY : core/rans_bit_decoder.cc.i

core/rans_bit_decoder.s: core/rans_bit_decoder.cc.s

.PHONY : core/rans_bit_decoder.s

# target to generate assembly for a file
core/rans_bit_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/rans_bit_decoder.cc.s
.PHONY : core/rans_bit_decoder.cc.s

core/rans_bit_encoder.o: core/rans_bit_encoder.cc.o

.PHONY : core/rans_bit_encoder.o

# target to build an object file
core/rans_bit_encoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/rans_bit_encoder.cc.o
.PHONY : core/rans_bit_encoder.cc.o

core/rans_bit_encoder.i: core/rans_bit_encoder.cc.i

.PHONY : core/rans_bit_encoder.i

# target to preprocess a source file
core/rans_bit_encoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/rans_bit_encoder.cc.i
.PHONY : core/rans_bit_encoder.cc.i

core/rans_bit_encoder.s: core/rans_bit_encoder.cc.s

.PHONY : core/rans_bit_encoder.s

# target to generate assembly for a file
core/rans_bit_encoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/rans_bit_encoder.cc.s
.PHONY : core/rans_bit_encoder.cc.s

core/shannon_entropy.o: core/shannon_entropy.cc.o

.PHONY : core/shannon_entropy.o

# target to build an object file
core/shannon_entropy.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/shannon_entropy.cc.o
.PHONY : core/shannon_entropy.cc.o

core/shannon_entropy.i: core/shannon_entropy.cc.i

.PHONY : core/shannon_entropy.i

# target to preprocess a source file
core/shannon_entropy.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/shannon_entropy.cc.i
.PHONY : core/shannon_entropy.cc.i

core/shannon_entropy.s: core/shannon_entropy.cc.s

.PHONY : core/shannon_entropy.s

# target to generate assembly for a file
core/shannon_entropy.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/shannon_entropy.cc.s
.PHONY : core/shannon_entropy.cc.s

core/symbol_bit_decoder.o: core/symbol_bit_decoder.cc.o

.PHONY : core/symbol_bit_decoder.o

# target to build an object file
core/symbol_bit_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_bit_decoder.cc.o
.PHONY : core/symbol_bit_decoder.cc.o

core/symbol_bit_decoder.i: core/symbol_bit_decoder.cc.i

.PHONY : core/symbol_bit_decoder.i

# target to preprocess a source file
core/symbol_bit_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_bit_decoder.cc.i
.PHONY : core/symbol_bit_decoder.cc.i

core/symbol_bit_decoder.s: core/symbol_bit_decoder.cc.s

.PHONY : core/symbol_bit_decoder.s

# target to generate assembly for a file
core/symbol_bit_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_bit_decoder.cc.s
.PHONY : core/symbol_bit_decoder.cc.s

core/symbol_bit_encoder.o: core/symbol_bit_encoder.cc.o

.PHONY : core/symbol_bit_encoder.o

# target to build an object file
core/symbol_bit_encoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_bit_encoder.cc.o
.PHONY : core/symbol_bit_encoder.cc.o

core/symbol_bit_encoder.i: core/symbol_bit_encoder.cc.i

.PHONY : core/symbol_bit_encoder.i

# target to preprocess a source file
core/symbol_bit_encoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_bit_encoder.cc.i
.PHONY : core/symbol_bit_encoder.cc.i

core/symbol_bit_encoder.s: core/symbol_bit_encoder.cc.s

.PHONY : core/symbol_bit_encoder.s

# target to generate assembly for a file
core/symbol_bit_encoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_bit_encoder.cc.s
.PHONY : core/symbol_bit_encoder.cc.s

core/symbol_decoding.o: core/symbol_decoding.cc.o

.PHONY : core/symbol_decoding.o

# target to build an object file
core/symbol_decoding.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_decoding.cc.o
.PHONY : core/symbol_decoding.cc.o

core/symbol_decoding.i: core/symbol_decoding.cc.i

.PHONY : core/symbol_decoding.i

# target to preprocess a source file
core/symbol_decoding.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_decoding.cc.i
.PHONY : core/symbol_decoding.cc.i

core/symbol_decoding.s: core/symbol_decoding.cc.s

.PHONY : core/symbol_decoding.s

# target to generate assembly for a file
core/symbol_decoding.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_decoding.cc.s
.PHONY : core/symbol_decoding.cc.s

core/symbol_encoding.o: core/symbol_encoding.cc.o

.PHONY : core/symbol_encoding.o

# target to build an object file
core/symbol_encoding.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_encoding.cc.o
.PHONY : core/symbol_encoding.cc.o

core/symbol_encoding.i: core/symbol_encoding.cc.i

.PHONY : core/symbol_encoding.i

# target to preprocess a source file
core/symbol_encoding.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_encoding.cc.i
.PHONY : core/symbol_encoding.cc.i

core/symbol_encoding.s: core/symbol_encoding.cc.s

.PHONY : core/symbol_encoding.s

# target to generate assembly for a file
core/symbol_encoding.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/core/symbol_encoding.cc.s
.PHONY : core/symbol_encoding.cc.s

draco_version.o: draco_version.cc.o

.PHONY : draco_version.o

# target to build an object file
draco_version.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/draco_version.cc.o
.PHONY : draco_version.cc.o

draco_version.i: draco_version.cc.i

.PHONY : draco_version.i

# target to preprocess a source file
draco_version.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/draco_version.cc.i
.PHONY : draco_version.cc.i

draco_version.s: draco_version.cc.s

.PHONY : draco_version.s

# target to generate assembly for a file
draco_version.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/draco_version.cc.s
.PHONY : draco_version.cc.s

finalize_js_tracker.o: finalize_js_tracker.c.o

.PHONY : finalize_js_tracker.o

# target to build an object file
finalize_js_tracker.c.o:
	$(MAKE) -f CMakeFiles/draco_decoder_2_finalize_js.dir/build.make CMakeFiles/draco_decoder_2_finalize_js.dir/finalize_js_tracker.c.o
.PHONY : finalize_js_tracker.c.o

finalize_js_tracker.i: finalize_js_tracker.c.i

.PHONY : finalize_js_tracker.i

# target to preprocess a source file
finalize_js_tracker.c.i:
	$(MAKE) -f CMakeFiles/draco_decoder_2_finalize_js.dir/build.make CMakeFiles/draco_decoder_2_finalize_js.dir/finalize_js_tracker.c.i
.PHONY : finalize_js_tracker.c.i

finalize_js_tracker.s: finalize_js_tracker.c.s

.PHONY : finalize_js_tracker.s

# target to generate assembly for a file
finalize_js_tracker.c.s:
	$(MAKE) -f CMakeFiles/draco_decoder_2_finalize_js.dir/build.make CMakeFiles/draco_decoder_2_finalize_js.dir/finalize_js_tracker.c.s
.PHONY : finalize_js_tracker.c.s

glue_js_tracker.o: glue_js_tracker.c.o

.PHONY : glue_js_tracker.o

# target to build an object file
glue_js_tracker.c.o:
	$(MAKE) -f CMakeFiles/draco_decoder_1_glue_js.dir/build.make CMakeFiles/draco_decoder_1_glue_js.dir/glue_js_tracker.c.o
.PHONY : glue_js_tracker.c.o

glue_js_tracker.i: glue_js_tracker.c.i

.PHONY : glue_js_tracker.i

# target to preprocess a source file
glue_js_tracker.c.i:
	$(MAKE) -f CMakeFiles/draco_decoder_1_glue_js.dir/build.make CMakeFiles/draco_decoder_1_glue_js.dir/glue_js_tracker.c.i
.PHONY : glue_js_tracker.c.i

glue_js_tracker.s: glue_js_tracker.c.s

.PHONY : glue_js_tracker.s

# target to generate assembly for a file
glue_js_tracker.c.s:
	$(MAKE) -f CMakeFiles/draco_decoder_1_glue_js.dir/build.make CMakeFiles/draco_decoder_1_glue_js.dir/glue_js_tracker.c.s
.PHONY : glue_js_tracker.c.s

io/mesh_io.o: io/mesh_io.cc.o

.PHONY : io/mesh_io.o

# target to build an object file
io/mesh_io.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/mesh_io.cc.o
.PHONY : io/mesh_io.cc.o

io/mesh_io.i: io/mesh_io.cc.i

.PHONY : io/mesh_io.i

# target to preprocess a source file
io/mesh_io.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/mesh_io.cc.i
.PHONY : io/mesh_io.cc.i

io/mesh_io.s: io/mesh_io.cc.s

.PHONY : io/mesh_io.s

# target to generate assembly for a file
io/mesh_io.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/mesh_io.cc.s
.PHONY : io/mesh_io.cc.s

io/obj_decoder.o: io/obj_decoder.cc.o

.PHONY : io/obj_decoder.o

# target to build an object file
io/obj_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/obj_decoder.cc.o
.PHONY : io/obj_decoder.cc.o

io/obj_decoder.i: io/obj_decoder.cc.i

.PHONY : io/obj_decoder.i

# target to preprocess a source file
io/obj_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/obj_decoder.cc.i
.PHONY : io/obj_decoder.cc.i

io/obj_decoder.s: io/obj_decoder.cc.s

.PHONY : io/obj_decoder.s

# target to generate assembly for a file
io/obj_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/obj_decoder.cc.s
.PHONY : io/obj_decoder.cc.s

io/obj_encoder.o: io/obj_encoder.cc.o

.PHONY : io/obj_encoder.o

# target to build an object file
io/obj_encoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/obj_encoder.cc.o
.PHONY : io/obj_encoder.cc.o

io/obj_encoder.i: io/obj_encoder.cc.i

.PHONY : io/obj_encoder.i

# target to preprocess a source file
io/obj_encoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/obj_encoder.cc.i
.PHONY : io/obj_encoder.cc.i

io/obj_encoder.s: io/obj_encoder.cc.s

.PHONY : io/obj_encoder.s

# target to generate assembly for a file
io/obj_encoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/obj_encoder.cc.s
.PHONY : io/obj_encoder.cc.s

io/parser_utils.o: io/parser_utils.cc.o

.PHONY : io/parser_utils.o

# target to build an object file
io/parser_utils.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/parser_utils.cc.o
.PHONY : io/parser_utils.cc.o

io/parser_utils.i: io/parser_utils.cc.i

.PHONY : io/parser_utils.i

# target to preprocess a source file
io/parser_utils.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/parser_utils.cc.i
.PHONY : io/parser_utils.cc.i

io/parser_utils.s: io/parser_utils.cc.s

.PHONY : io/parser_utils.s

# target to generate assembly for a file
io/parser_utils.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/parser_utils.cc.s
.PHONY : io/parser_utils.cc.s

io/ply_decoder.o: io/ply_decoder.cc.o

.PHONY : io/ply_decoder.o

# target to build an object file
io/ply_decoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_decoder.cc.o
.PHONY : io/ply_decoder.cc.o

io/ply_decoder.i: io/ply_decoder.cc.i

.PHONY : io/ply_decoder.i

# target to preprocess a source file
io/ply_decoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_decoder.cc.i
.PHONY : io/ply_decoder.cc.i

io/ply_decoder.s: io/ply_decoder.cc.s

.PHONY : io/ply_decoder.s

# target to generate assembly for a file
io/ply_decoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_decoder.cc.s
.PHONY : io/ply_decoder.cc.s

io/ply_encoder.o: io/ply_encoder.cc.o

.PHONY : io/ply_encoder.o

# target to build an object file
io/ply_encoder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_encoder.cc.o
.PHONY : io/ply_encoder.cc.o

io/ply_encoder.i: io/ply_encoder.cc.i

.PHONY : io/ply_encoder.i

# target to preprocess a source file
io/ply_encoder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_encoder.cc.i
.PHONY : io/ply_encoder.cc.i

io/ply_encoder.s: io/ply_encoder.cc.s

.PHONY : io/ply_encoder.s

# target to generate assembly for a file
io/ply_encoder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_encoder.cc.s
.PHONY : io/ply_encoder.cc.s

io/ply_reader.o: io/ply_reader.cc.o

.PHONY : io/ply_reader.o

# target to build an object file
io/ply_reader.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_reader.cc.o
.PHONY : io/ply_reader.cc.o

io/ply_reader.i: io/ply_reader.cc.i

.PHONY : io/ply_reader.i

# target to preprocess a source file
io/ply_reader.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_reader.cc.i
.PHONY : io/ply_reader.cc.i

io/ply_reader.s: io/ply_reader.cc.s

.PHONY : io/ply_reader.s

# target to generate assembly for a file
io/ply_reader.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/ply_reader.cc.s
.PHONY : io/ply_reader.cc.s

io/point_cloud_io.o: io/point_cloud_io.cc.o

.PHONY : io/point_cloud_io.o

# target to build an object file
io/point_cloud_io.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/point_cloud_io.cc.o
.PHONY : io/point_cloud_io.cc.o

io/point_cloud_io.i: io/point_cloud_io.cc.i

.PHONY : io/point_cloud_io.i

# target to preprocess a source file
io/point_cloud_io.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/point_cloud_io.cc.i
.PHONY : io/point_cloud_io.cc.i

io/point_cloud_io.s: io/point_cloud_io.cc.s

.PHONY : io/point_cloud_io.s

# target to generate assembly for a file
io/point_cloud_io.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/io/point_cloud_io.cc.s
.PHONY : io/point_cloud_io.cc.s

javascript/emscripten/draco_glue_wrapper.o: javascript/emscripten/draco_glue_wrapper.cc.o

.PHONY : javascript/emscripten/draco_glue_wrapper.o

# target to build an object file
javascript/emscripten/draco_glue_wrapper.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/javascript/emscripten/draco_glue_wrapper.cc.o
.PHONY : javascript/emscripten/draco_glue_wrapper.cc.o

javascript/emscripten/draco_glue_wrapper.i: javascript/emscripten/draco_glue_wrapper.cc.i

.PHONY : javascript/emscripten/draco_glue_wrapper.i

# target to preprocess a source file
javascript/emscripten/draco_glue_wrapper.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/javascript/emscripten/draco_glue_wrapper.cc.i
.PHONY : javascript/emscripten/draco_glue_wrapper.cc.i

javascript/emscripten/draco_glue_wrapper.s: javascript/emscripten/draco_glue_wrapper.cc.s

.PHONY : javascript/emscripten/draco_glue_wrapper.s

# target to generate assembly for a file
javascript/emscripten/draco_glue_wrapper.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/javascript/emscripten/draco_glue_wrapper.cc.s
.PHONY : javascript/emscripten/draco_glue_wrapper.cc.s

javascript/emscripten/webidl_wrapper.o: javascript/emscripten/webidl_wrapper.cc.o

.PHONY : javascript/emscripten/webidl_wrapper.o

# target to build an object file
javascript/emscripten/webidl_wrapper.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/javascript/emscripten/webidl_wrapper.cc.o
.PHONY : javascript/emscripten/webidl_wrapper.cc.o

javascript/emscripten/webidl_wrapper.i: javascript/emscripten/webidl_wrapper.cc.i

.PHONY : javascript/emscripten/webidl_wrapper.i

# target to preprocess a source file
javascript/emscripten/webidl_wrapper.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/javascript/emscripten/webidl_wrapper.cc.i
.PHONY : javascript/emscripten/webidl_wrapper.cc.i

javascript/emscripten/webidl_wrapper.s: javascript/emscripten/webidl_wrapper.cc.s

.PHONY : javascript/emscripten/webidl_wrapper.s

# target to generate assembly for a file
javascript/emscripten/webidl_wrapper.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/javascript/emscripten/webidl_wrapper.cc.s
.PHONY : javascript/emscripten/webidl_wrapper.cc.s

mesh/corner_table.o: mesh/corner_table.cc.o

.PHONY : mesh/corner_table.o

# target to build an object file
mesh/corner_table.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/corner_table.cc.o
.PHONY : mesh/corner_table.cc.o

mesh/corner_table.i: mesh/corner_table.cc.i

.PHONY : mesh/corner_table.i

# target to preprocess a source file
mesh/corner_table.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/corner_table.cc.i
.PHONY : mesh/corner_table.cc.i

mesh/corner_table.s: mesh/corner_table.cc.s

.PHONY : mesh/corner_table.s

# target to generate assembly for a file
mesh/corner_table.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/corner_table.cc.s
.PHONY : mesh/corner_table.cc.s

mesh/mesh.o: mesh/mesh.cc.o

.PHONY : mesh/mesh.o

# target to build an object file
mesh/mesh.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh.cc.o
.PHONY : mesh/mesh.cc.o

mesh/mesh.i: mesh/mesh.cc.i

.PHONY : mesh/mesh.i

# target to preprocess a source file
mesh/mesh.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh.cc.i
.PHONY : mesh/mesh.cc.i

mesh/mesh.s: mesh/mesh.cc.s

.PHONY : mesh/mesh.s

# target to generate assembly for a file
mesh/mesh.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh.cc.s
.PHONY : mesh/mesh.cc.s

mesh/mesh_are_equivalent.o: mesh/mesh_are_equivalent.cc.o

.PHONY : mesh/mesh_are_equivalent.o

# target to build an object file
mesh/mesh_are_equivalent.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_are_equivalent.cc.o
.PHONY : mesh/mesh_are_equivalent.cc.o

mesh/mesh_are_equivalent.i: mesh/mesh_are_equivalent.cc.i

.PHONY : mesh/mesh_are_equivalent.i

# target to preprocess a source file
mesh/mesh_are_equivalent.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_are_equivalent.cc.i
.PHONY : mesh/mesh_are_equivalent.cc.i

mesh/mesh_are_equivalent.s: mesh/mesh_are_equivalent.cc.s

.PHONY : mesh/mesh_are_equivalent.s

# target to generate assembly for a file
mesh/mesh_are_equivalent.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_are_equivalent.cc.s
.PHONY : mesh/mesh_are_equivalent.cc.s

mesh/mesh_attribute_corner_table.o: mesh/mesh_attribute_corner_table.cc.o

.PHONY : mesh/mesh_attribute_corner_table.o

# target to build an object file
mesh/mesh_attribute_corner_table.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_attribute_corner_table.cc.o
.PHONY : mesh/mesh_attribute_corner_table.cc.o

mesh/mesh_attribute_corner_table.i: mesh/mesh_attribute_corner_table.cc.i

.PHONY : mesh/mesh_attribute_corner_table.i

# target to preprocess a source file
mesh/mesh_attribute_corner_table.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_attribute_corner_table.cc.i
.PHONY : mesh/mesh_attribute_corner_table.cc.i

mesh/mesh_attribute_corner_table.s: mesh/mesh_attribute_corner_table.cc.s

.PHONY : mesh/mesh_attribute_corner_table.s

# target to generate assembly for a file
mesh/mesh_attribute_corner_table.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_attribute_corner_table.cc.s
.PHONY : mesh/mesh_attribute_corner_table.cc.s

mesh/mesh_cleanup.o: mesh/mesh_cleanup.cc.o

.PHONY : mesh/mesh_cleanup.o

# target to build an object file
mesh/mesh_cleanup.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_cleanup.cc.o
.PHONY : mesh/mesh_cleanup.cc.o

mesh/mesh_cleanup.i: mesh/mesh_cleanup.cc.i

.PHONY : mesh/mesh_cleanup.i

# target to preprocess a source file
mesh/mesh_cleanup.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_cleanup.cc.i
.PHONY : mesh/mesh_cleanup.cc.i

mesh/mesh_cleanup.s: mesh/mesh_cleanup.cc.s

.PHONY : mesh/mesh_cleanup.s

# target to generate assembly for a file
mesh/mesh_cleanup.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_cleanup.cc.s
.PHONY : mesh/mesh_cleanup.cc.s

mesh/mesh_misc_functions.o: mesh/mesh_misc_functions.cc.o

.PHONY : mesh/mesh_misc_functions.o

# target to build an object file
mesh/mesh_misc_functions.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_misc_functions.cc.o
.PHONY : mesh/mesh_misc_functions.cc.o

mesh/mesh_misc_functions.i: mesh/mesh_misc_functions.cc.i

.PHONY : mesh/mesh_misc_functions.i

# target to preprocess a source file
mesh/mesh_misc_functions.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_misc_functions.cc.i
.PHONY : mesh/mesh_misc_functions.cc.i

mesh/mesh_misc_functions.s: mesh/mesh_misc_functions.cc.s

.PHONY : mesh/mesh_misc_functions.s

# target to generate assembly for a file
mesh/mesh_misc_functions.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/mesh_misc_functions.cc.s
.PHONY : mesh/mesh_misc_functions.cc.s

mesh/triangle_soup_mesh_builder.o: mesh/triangle_soup_mesh_builder.cc.o

.PHONY : mesh/triangle_soup_mesh_builder.o

# target to build an object file
mesh/triangle_soup_mesh_builder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/triangle_soup_mesh_builder.cc.o
.PHONY : mesh/triangle_soup_mesh_builder.cc.o

mesh/triangle_soup_mesh_builder.i: mesh/triangle_soup_mesh_builder.cc.i

.PHONY : mesh/triangle_soup_mesh_builder.i

# target to preprocess a source file
mesh/triangle_soup_mesh_builder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/triangle_soup_mesh_builder.cc.i
.PHONY : mesh/triangle_soup_mesh_builder.cc.i

mesh/triangle_soup_mesh_builder.s: mesh/triangle_soup_mesh_builder.cc.s

.PHONY : mesh/triangle_soup_mesh_builder.s

# target to generate assembly for a file
mesh/triangle_soup_mesh_builder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/mesh/triangle_soup_mesh_builder.cc.s
.PHONY : mesh/triangle_soup_mesh_builder.cc.s

point_cloud/geometry_attribute.o: point_cloud/geometry_attribute.cc.o

.PHONY : point_cloud/geometry_attribute.o

# target to build an object file
point_cloud/geometry_attribute.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/geometry_attribute.cc.o
.PHONY : point_cloud/geometry_attribute.cc.o

point_cloud/geometry_attribute.i: point_cloud/geometry_attribute.cc.i

.PHONY : point_cloud/geometry_attribute.i

# target to preprocess a source file
point_cloud/geometry_attribute.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/geometry_attribute.cc.i
.PHONY : point_cloud/geometry_attribute.cc.i

point_cloud/geometry_attribute.s: point_cloud/geometry_attribute.cc.s

.PHONY : point_cloud/geometry_attribute.s

# target to generate assembly for a file
point_cloud/geometry_attribute.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/geometry_attribute.cc.s
.PHONY : point_cloud/geometry_attribute.cc.s

point_cloud/point_attribute.o: point_cloud/point_attribute.cc.o

.PHONY : point_cloud/point_attribute.o

# target to build an object file
point_cloud/point_attribute.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_attribute.cc.o
.PHONY : point_cloud/point_attribute.cc.o

point_cloud/point_attribute.i: point_cloud/point_attribute.cc.i

.PHONY : point_cloud/point_attribute.i

# target to preprocess a source file
point_cloud/point_attribute.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_attribute.cc.i
.PHONY : point_cloud/point_attribute.cc.i

point_cloud/point_attribute.s: point_cloud/point_attribute.cc.s

.PHONY : point_cloud/point_attribute.s

# target to generate assembly for a file
point_cloud/point_attribute.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_attribute.cc.s
.PHONY : point_cloud/point_attribute.cc.s

point_cloud/point_cloud.o: point_cloud/point_cloud.cc.o

.PHONY : point_cloud/point_cloud.o

# target to build an object file
point_cloud/point_cloud.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_cloud.cc.o
.PHONY : point_cloud/point_cloud.cc.o

point_cloud/point_cloud.i: point_cloud/point_cloud.cc.i

.PHONY : point_cloud/point_cloud.i

# target to preprocess a source file
point_cloud/point_cloud.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_cloud.cc.i
.PHONY : point_cloud/point_cloud.cc.i

point_cloud/point_cloud.s: point_cloud/point_cloud.cc.s

.PHONY : point_cloud/point_cloud.s

# target to generate assembly for a file
point_cloud/point_cloud.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_cloud.cc.s
.PHONY : point_cloud/point_cloud.cc.s

point_cloud/point_cloud_builder.o: point_cloud/point_cloud_builder.cc.o

.PHONY : point_cloud/point_cloud_builder.o

# target to build an object file
point_cloud/point_cloud_builder.cc.o:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_cloud_builder.cc.o
.PHONY : point_cloud/point_cloud_builder.cc.o

point_cloud/point_cloud_builder.i: point_cloud/point_cloud_builder.cc.i

.PHONY : point_cloud/point_cloud_builder.i

# target to preprocess a source file
point_cloud/point_cloud_builder.cc.i:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_cloud_builder.cc.i
.PHONY : point_cloud/point_cloud_builder.cc.i

point_cloud/point_cloud_builder.s: point_cloud/point_cloud_builder.cc.s

.PHONY : point_cloud/point_cloud_builder.s

# target to generate assembly for a file
point_cloud/point_cloud_builder.cc.s:
	$(MAKE) -f CMakeFiles/draco_decoder.dir/build.make CMakeFiles/draco_decoder.dir/point_cloud/point_cloud_builder.cc.s
.PHONY : point_cloud/point_cloud_builder.cc.s

prepareCallbacks_js_tracker.o: prepareCallbacks_js_tracker.c.o

.PHONY : prepareCallbacks_js_tracker.o

# target to build an object file
prepareCallbacks_js_tracker.c.o:
	$(MAKE) -f CMakeFiles/draco_decoder_1_prepareCallbacks_js.dir/build.make CMakeFiles/draco_decoder_1_prepareCallbacks_js.dir/prepareCallbacks_js_tracker.c.o
.PHONY : prepareCallbacks_js_tracker.c.o

prepareCallbacks_js_tracker.i: prepareCallbacks_js_tracker.c.i

.PHONY : prepareCallbacks_js_tracker.i

# target to preprocess a source file
prepareCallbacks_js_tracker.c.i:
	$(MAKE) -f CMakeFiles/draco_decoder_1_prepareCallbacks_js.dir/build.make CMakeFiles/draco_decoder_1_prepareCallbacks_js.dir/prepareCallbacks_js_tracker.c.i
.PHONY : prepareCallbacks_js_tracker.c.i

prepareCallbacks_js_tracker.s: prepareCallbacks_js_tracker.c.s

.PHONY : prepareCallbacks_js_tracker.s

# target to generate assembly for a file
prepareCallbacks_js_tracker.c.s:
	$(MAKE) -f CMakeFiles/draco_decoder_1_prepareCallbacks_js.dir/build.make CMakeFiles/draco_decoder_1_prepareCallbacks_js.dir/prepareCallbacks_js_tracker.c.s
.PHONY : prepareCallbacks_js_tracker.c.s

version_js_tracker.o: version_js_tracker.c.o

.PHONY : version_js_tracker.o

# target to build an object file
version_js_tracker.c.o:
	$(MAKE) -f CMakeFiles/draco_decoder_2_version_js.dir/build.make CMakeFiles/draco_decoder_2_version_js.dir/version_js_tracker.c.o
.PHONY : version_js_tracker.c.o

version_js_tracker.i: version_js_tracker.c.i

.PHONY : version_js_tracker.i

# target to preprocess a source file
version_js_tracker.c.i:
	$(MAKE) -f CMakeFiles/draco_decoder_2_version_js.dir/build.make CMakeFiles/draco_decoder_2_version_js.dir/version_js_tracker.c.i
.PHONY : version_js_tracker.c.i

version_js_tracker.s: version_js_tracker.c.s

.PHONY : version_js_tracker.s

# target to generate assembly for a file
version_js_tracker.c.s:
	$(MAKE) -f CMakeFiles/draco_decoder_2_version_js.dir/build.make CMakeFiles/draco_decoder_2_version_js.dir/version_js_tracker.c.s
.PHONY : version_js_tracker.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... draco_decoder"
	@echo "... draco_decoder_2_finalize_js"
	@echo "... draco_decoder_1_glue_js"
	@echo "... draco_decoder_2_version_js"
	@echo "... draco_decoder_1_prepareCallbacks_js"
	@echo "... compression/attributes/attributes_decoder.o"
	@echo "... compression/attributes/attributes_decoder.i"
	@echo "... compression/attributes/attributes_decoder.s"
	@echo "... compression/attributes/kd_tree_attributes_decoder.o"
	@echo "... compression/attributes/kd_tree_attributes_decoder.i"
	@echo "... compression/attributes/kd_tree_attributes_decoder.s"
	@echo "... compression/attributes/sequential_attribute_decoder.o"
	@echo "... compression/attributes/sequential_attribute_decoder.i"
	@echo "... compression/attributes/sequential_attribute_decoder.s"
	@echo "... compression/attributes/sequential_attribute_decoders_controller.o"
	@echo "... compression/attributes/sequential_attribute_decoders_controller.i"
	@echo "... compression/attributes/sequential_attribute_decoders_controller.s"
	@echo "... compression/attributes/sequential_integer_attribute_decoder.o"
	@echo "... compression/attributes/sequential_integer_attribute_decoder.i"
	@echo "... compression/attributes/sequential_integer_attribute_decoder.s"
	@echo "... compression/attributes/sequential_normal_attribute_decoder.o"
	@echo "... compression/attributes/sequential_normal_attribute_decoder.i"
	@echo "... compression/attributes/sequential_normal_attribute_decoder.s"
	@echo "... compression/attributes/sequential_quantization_attribute_decoder.o"
	@echo "... compression/attributes/sequential_quantization_attribute_decoder.i"
	@echo "... compression/attributes/sequential_quantization_attribute_decoder.s"
	@echo "... compression/decode.o"
	@echo "... compression/decode.i"
	@echo "... compression/decode.s"
	@echo "... compression/mesh/mesh_decoder.o"
	@echo "... compression/mesh/mesh_decoder.i"
	@echo "... compression/mesh/mesh_decoder.s"
	@echo "... compression/mesh/mesh_edgebreaker_decoder.o"
	@echo "... compression/mesh/mesh_edgebreaker_decoder.i"
	@echo "... compression/mesh/mesh_edgebreaker_decoder.s"
	@echo "... compression/mesh/mesh_edgebreaker_decoder_impl.o"
	@echo "... compression/mesh/mesh_edgebreaker_decoder_impl.i"
	@echo "... compression/mesh/mesh_edgebreaker_decoder_impl.s"
	@echo "... compression/mesh/mesh_sequential_decoder.o"
	@echo "... compression/mesh/mesh_sequential_decoder.i"
	@echo "... compression/mesh/mesh_sequential_decoder.s"
	@echo "... compression/point_cloud/algorithms/float_points_tree_decoder.o"
	@echo "... compression/point_cloud/algorithms/float_points_tree_decoder.i"
	@echo "... compression/point_cloud/algorithms/float_points_tree_decoder.s"
	@echo "... compression/point_cloud/algorithms/integer_points_kd_tree_decoder.o"
	@echo "... compression/point_cloud/algorithms/integer_points_kd_tree_decoder.i"
	@echo "... compression/point_cloud/algorithms/integer_points_kd_tree_decoder.s"
	@echo "... compression/point_cloud/point_cloud_decoder.o"
	@echo "... compression/point_cloud/point_cloud_decoder.i"
	@echo "... compression/point_cloud/point_cloud_decoder.s"
	@echo "... compression/point_cloud/point_cloud_kd_tree_decoder.o"
	@echo "... compression/point_cloud/point_cloud_kd_tree_decoder.i"
	@echo "... compression/point_cloud/point_cloud_kd_tree_decoder.s"
	@echo "... compression/point_cloud/point_cloud_sequential_decoder.o"
	@echo "... compression/point_cloud/point_cloud_sequential_decoder.i"
	@echo "... compression/point_cloud/point_cloud_sequential_decoder.s"
	@echo "... core/adaptive_rans_bit_decoder.o"
	@echo "... core/adaptive_rans_bit_decoder.i"
	@echo "... core/adaptive_rans_bit_decoder.s"
	@echo "... core/adaptive_rans_bit_encoder.o"
	@echo "... core/adaptive_rans_bit_encoder.i"
	@echo "... core/adaptive_rans_bit_encoder.s"
	@echo "... core/bit_coder.o"
	@echo "... core/bit_coder.i"
	@echo "... core/bit_coder.s"
	@echo "... core/cycle_timer.o"
	@echo "... core/cycle_timer.i"
	@echo "... core/cycle_timer.s"
	@echo "... core/data_buffer.o"
	@echo "... core/data_buffer.i"
	@echo "... core/data_buffer.s"
	@echo "... core/decoder_buffer.o"
	@echo "... core/decoder_buffer.i"
	@echo "... core/decoder_buffer.s"
	@echo "... core/direct_bit_decoder.o"
	@echo "... core/direct_bit_decoder.i"
	@echo "... core/direct_bit_decoder.s"
	@echo "... core/direct_bit_encoder.o"
	@echo "... core/direct_bit_encoder.i"
	@echo "... core/direct_bit_encoder.s"
	@echo "... core/divide.o"
	@echo "... core/divide.i"
	@echo "... core/divide.s"
	@echo "... core/draco_types.o"
	@echo "... core/draco_types.i"
	@echo "... core/draco_types.s"
	@echo "... core/encoder_buffer.o"
	@echo "... core/encoder_buffer.i"
	@echo "... core/encoder_buffer.s"
	@echo "... core/hash_utils.o"
	@echo "... core/hash_utils.i"
	@echo "... core/hash_utils.s"
	@echo "... core/options.o"
	@echo "... core/options.i"
	@echo "... core/options.s"
	@echo "... core/quantization_utils.o"
	@echo "... core/quantization_utils.i"
	@echo "... core/quantization_utils.s"
	@echo "... core/rans_bit_decoder.o"
	@echo "... core/rans_bit_decoder.i"
	@echo "... core/rans_bit_decoder.s"
	@echo "... core/rans_bit_encoder.o"
	@echo "... core/rans_bit_encoder.i"
	@echo "... core/rans_bit_encoder.s"
	@echo "... core/shannon_entropy.o"
	@echo "... core/shannon_entropy.i"
	@echo "... core/shannon_entropy.s"
	@echo "... core/symbol_bit_decoder.o"
	@echo "... core/symbol_bit_decoder.i"
	@echo "... core/symbol_bit_decoder.s"
	@echo "... core/symbol_bit_encoder.o"
	@echo "... core/symbol_bit_encoder.i"
	@echo "... core/symbol_bit_encoder.s"
	@echo "... core/symbol_decoding.o"
	@echo "... core/symbol_decoding.i"
	@echo "... core/symbol_decoding.s"
	@echo "... core/symbol_encoding.o"
	@echo "... core/symbol_encoding.i"
	@echo "... core/symbol_encoding.s"
	@echo "... draco_version.o"
	@echo "... draco_version.i"
	@echo "... draco_version.s"
	@echo "... finalize_js_tracker.o"
	@echo "... finalize_js_tracker.i"
	@echo "... finalize_js_tracker.s"
	@echo "... glue_js_tracker.o"
	@echo "... glue_js_tracker.i"
	@echo "... glue_js_tracker.s"
	@echo "... io/mesh_io.o"
	@echo "... io/mesh_io.i"
	@echo "... io/mesh_io.s"
	@echo "... io/obj_decoder.o"
	@echo "... io/obj_decoder.i"
	@echo "... io/obj_decoder.s"
	@echo "... io/obj_encoder.o"
	@echo "... io/obj_encoder.i"
	@echo "... io/obj_encoder.s"
	@echo "... io/parser_utils.o"
	@echo "... io/parser_utils.i"
	@echo "... io/parser_utils.s"
	@echo "... io/ply_decoder.o"
	@echo "... io/ply_decoder.i"
	@echo "... io/ply_decoder.s"
	@echo "... io/ply_encoder.o"
	@echo "... io/ply_encoder.i"
	@echo "... io/ply_encoder.s"
	@echo "... io/ply_reader.o"
	@echo "... io/ply_reader.i"
	@echo "... io/ply_reader.s"
	@echo "... io/point_cloud_io.o"
	@echo "... io/point_cloud_io.i"
	@echo "... io/point_cloud_io.s"
	@echo "... javascript/emscripten/draco_glue_wrapper.o"
	@echo "... javascript/emscripten/draco_glue_wrapper.i"
	@echo "... javascript/emscripten/draco_glue_wrapper.s"
	@echo "... javascript/emscripten/webidl_wrapper.o"
	@echo "... javascript/emscripten/webidl_wrapper.i"
	@echo "... javascript/emscripten/webidl_wrapper.s"
	@echo "... mesh/corner_table.o"
	@echo "... mesh/corner_table.i"
	@echo "... mesh/corner_table.s"
	@echo "... mesh/mesh.o"
	@echo "... mesh/mesh.i"
	@echo "... mesh/mesh.s"
	@echo "... mesh/mesh_are_equivalent.o"
	@echo "... mesh/mesh_are_equivalent.i"
	@echo "... mesh/mesh_are_equivalent.s"
	@echo "... mesh/mesh_attribute_corner_table.o"
	@echo "... mesh/mesh_attribute_corner_table.i"
	@echo "... mesh/mesh_attribute_corner_table.s"
	@echo "... mesh/mesh_cleanup.o"
	@echo "... mesh/mesh_cleanup.i"
	@echo "... mesh/mesh_cleanup.s"
	@echo "... mesh/mesh_misc_functions.o"
	@echo "... mesh/mesh_misc_functions.i"
	@echo "... mesh/mesh_misc_functions.s"
	@echo "... mesh/triangle_soup_mesh_builder.o"
	@echo "... mesh/triangle_soup_mesh_builder.i"
	@echo "... mesh/triangle_soup_mesh_builder.s"
	@echo "... point_cloud/geometry_attribute.o"
	@echo "... point_cloud/geometry_attribute.i"
	@echo "... point_cloud/geometry_attribute.s"
	@echo "... point_cloud/point_attribute.o"
	@echo "... point_cloud/point_attribute.i"
	@echo "... point_cloud/point_attribute.s"
	@echo "... point_cloud/point_cloud.o"
	@echo "... point_cloud/point_cloud.i"
	@echo "... point_cloud/point_cloud.s"
	@echo "... point_cloud/point_cloud_builder.o"
	@echo "... point_cloud/point_cloud_builder.i"
	@echo "... point_cloud/point_cloud_builder.s"
	@echo "... prepareCallbacks_js_tracker.o"
	@echo "... prepareCallbacks_js_tracker.i"
	@echo "... prepareCallbacks_js_tracker.s"
	@echo "... version_js_tracker.o"
	@echo "... version_js_tracker.i"
	@echo "... version_js_tracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

